import pandas as pd
df = pd.read_csv("data/DrDoS_DNS.csv")
print("Dataset loaded successfully\n")
print("first 5 rows of the dataset:")
print(df.head(), "\n")
print("dataset shape(rows,columns):")
print(df.shape, "\n")
print("columns names:")
print(df.columns, "\n")
print("label distribution:")
print(df['label'].value_counts(), "\n")
print("Data types:")
print(df.dtypes, "\n")
print("missing values per column:")
print(df.isnull().sum())